server:
  port: 8082

spring:
  application:
    name: auth-service

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true

keycloak:
  token-url: http://localhost:8081/realms/securehub/protocol/openid-connect/token
  cert-url: http://localhost:8081/realms/securehub/protocol/openid-connect/certs
  logout-url: http://localhost:8081/realms/securehub/protocol/openid-connect/logout
  client-id: securehub-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
