server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/**

            - id: user-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/users/**
              filters:
                - JwtCookie

        default-filters:
          - PreserveHostHeader

logging:
   level:
     org.springframework.cloud.gateway: DEBUG
     reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway, health
  endpoint:
    gateway:
      enabled: true