server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 15s

      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - JwtCookie
                - name: CircuitBreaker
                  args:
                    name: userServiceCB
                    fallbackUri: forward:/fallback/user

            - id: organization-service
              uri: lb://ORGANIZATION-SERVICE
              predicates:
                - Path=/api/organizations/**
              filters:
                - JwtCookie
                - name: CircuitBreaker
                  args:
                    name: organizationServiceCB
                    fallbackUri: forward:/fallback/organization


        default-filters:
          - PreserveHostHeader

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      authServiceCB:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

      userServiceCB:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

      organizationServiceCB:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  timelimiter:
    instances:
      authServiceCB:
        timeout-duration: 10s

      userServiceCB:
        timeout-duration: 10s

      organizationServiceCB:
        timeout-duration: 10s

logging:
   level:
     org.springframework.cloud.gateway: DEBUG
     reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway, health
  endpoint:
    gateway:
      enabled: true