server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/securehub
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/securehub
