server:
  port: 8085

spring:
  application:
    name: organization-service

  datasource:
    url: jdbc:postgresql://localhost:5433/securehub_org_dev
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/securehub

  kafka:
    bootstrap-servers: localhost:9092

resilience4j:
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        randomized-wait-factor: 0.5

        retry-exceptions:
          - feign.RetryableException

        ignore-exceptions:
          - org.securehub.organizationservice.exception.UserNotFoundException
          - java.lang.IllegalArgumentException
          - org.springframework.security.access.AccessDeniedException

  circuitbreaker:
    instances:
      user-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
